django_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from miPortafolio import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('proyectos/', include('proyectos.urls')),
    path('', views.index, name = 'index'), 
    path('explaboral/', views.explaboral, name='explaboral'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectos/urls.py
from django.urls import path
from .views import project_render


app_name = 'proyectos'
urlpatterns =[
    path('', project_render, name= 'project' )
]

miPortafolio/models.py
from django.db import models

# Create your models here.

proyectos/models.py
from django.db import models

# Create your models here.
class Proyecto(models.Model):
    title = models.CharField(verbose_name='Titulo', max_length = 100)
    description= models.TextField(verbose_name='Descripcion', max_length = 1000)
    image= models.ImageField(upload_to = 'proyectos/images', verbose_name='Imagenes') 
    link = models.URLField(verbose_name='Direccion web', null=True, blank=True)
    created= models.DateTimeField(auto_now_add = True, verbose_name='Creacion')
    updated = models.DateTimeField(auto_now = True, verbose_name='Actualizacion')
    
    def __str__(self):
        return self.title

miPortafolio/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def explaboral(request):   
    return render(request, 'explaboral.html')

proyectos/views.py
from django.shortcuts import render, get_object_or_404
from .models import Proyecto
# Create your views here.

def project_render(request):
    projects= Proyecto.objects.all()
    return render(request, 'proyectos.html', {'projects': projects})

miPortafolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css'%}">
</head>
<body>
    
    {% include 'partials/navbar.html' %}
     
    <div class="container p-2">
        {% block content %}
    
        {% endblock%}

        <footer>
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-body p-2 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                                <p class="copyright text-muted text-center my-2"> &copy; 2024 · William Gonzalez Onatra (Ingeniero de Sistemas, Especialista en Seguridad Informatica)</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

miPortafolio/templates/explaboral.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Experiencia laboral</title>
    
</head>
<body>
    {% extends 'base.html' %}
    
    {% block content %}
    
    
    <div class="row p-3">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h5 class="text-center">Administrador de sistemas de informacion</h5>
                    <h6>Policia Nacional de Colombia - 21 años</h6>
                    <ul>
                        <li>Secretaría de Dirección, soporte administrativo y organizacional de alta dirección enfocado en objetivos estratégicos.</li>
                        <li>Gestión administrativa documental y recursos humanos.</li>
                        <li>Administrador de sistemas de informacion estratégica y operacional ARGIS, SIVVIC y SUNAMI.</li>
                        <li>Seguimiento y auditoría Interna a los planes de mejoramiento interno de la organización.</li>
                        <li>Desarrollo y seguimiento a la estrategia de identificación y atención a puntos críticos FIP.</li>
                        <li>Gestión equipos centro de Información Estratégico Policial CIEPS.</li>
                        
                      </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                
                       <div class="card-body p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h5 class="text-center">Area de Infraestructura Y Tecnologia</h5>
                    <h6>Coomeva Entidad Promotora de Salud - 1 año</h6>
                    <ul>
                        <li>Instalación y configuración de software y hardware en sistemas operativos Windows y Linux</li>
                        <li>Resolución de problemas técnicos, registro y seguimiento de incidencias.</li>
                        <li>Atención, soporte remoto y en sitio a los clientes internos de la organización a nivel nacional para el funcionamiento de la infraestructura tecnológica.</li>
                        <li>Diseño de páginas web en lenguajes de programación Python, Django HTML, CSS.</li>
                        
                      </ul> 
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

</body>
</html>

miPortafolio/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    
    {% extends 'base.html'%}
    
    {% block content %}

    {% load static %}
    <header class="row bg-primary-subtle">
        <div class="col-md-3 my-3 ">
            <img src="{% static 'miPortafolio/FOTO_W.jpg'%}" alt="" width="250" height="300">
        </div>
        <div class="col-md-8 my-5">
            <div class="card my-3">
                <div class="card-body p-2 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h1 class="text-center">WILLIAM GONZALEZ ONATRA</h1>
                    <p>Ingeniero de sistemas con Especialización en seguridad Informática y Tecnólogo en análisis y desarrollo de sistemas de información, soy una persona íntegra, con alto sentido de la responsabilidad, compromiso y honestidad, con capacidades para trabajar en equipo y criterio para apoyar la toma de decisiones, que permitan responder a las necesidades tecnológicas y optimización de los procesos en la empresa.</p>
                </div>
            </div>
        </div>
    </header>
    <div class="row primary-border-subtle">
        <div class="col-md-6 my-3" >
            <div class="card">
                <div class="card-body p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h4 class="text-center">Habilidades</h4>
                    <ul>
                        <li>Desarrollo Empresarial</li>
                        <li>Comunicación técnica y no técnica</li>
                        <li>Resolución de problemas</li>
                        <li>Gestion de Equipos</li>
                        <li>Adaptación al cambio</li>
                        <li>Manejo ofimática</li>
                        <li>Plataformas tecnológicas</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6 my-3">
            <div class="card">
                <div class="card-body p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h4 class="text-center">Educación</h4>
                    <ul>
                        <li>Especialización en seguridad Informática</li>
                        <li>Ingeniero de Sistemas</li>
                        <h6>Universidad Nacional Abierta y a Distancia UNAD</h6><br>
                        <li>Tecnólogo en Análisis y desarrollo de sistemas de información</li>
                        <h6>Servicio Nacional de Aprendizaje SENA</h6><br>                       
                    </ul>
                </div>
            </div>
        </div>
    
    </div>
    {% endblock%}
</body>
</html>

miPortafolio/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portafolio William Gonzalez Onatra</title>
</head>
<body>
    
    {% extends 'base.html'%}
    
    {% block content %}

    {% load static %}
    <header class="row bg-card-body p-2 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
        <div class="col-md-3 my-5">
            <img src="{% static 'miPortafolio/FOTO_W.jpg'%}" alt="" width="270" height="340">
        </div>
        <div class="col-md-9 my-1">
            <div class="card my-5">
                <div class="card-body p-2 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h1 class="text-center">WILLIAM GONZALEZ ONATRA</h1>
                    <h4 class="text-center"></h4>
                    <h4 class="text-center">Ingeniero de Sistemas | Especialista en Seguridad Informática</h4>
                    <p>Ingeniero de sistemas con especialización en seguridad informática y tecnología en análisis y desarrollo de sistemas de información. Con sólida formación académica, conocimientos técnicos y más de 20 años de experiencia en el sector público, me destaco en el liderazgo de equipos, gestión de proyectos, análisis de información estratégica y en implementación de políticas de seguridad de la información. Manejo herramientas avanzadas para el análisis de amenazas y la gestión de vulnerabilidades en ciberseguridad.</p>
                    
                    <h6>Correo: ssimon0710@gmail.com</h6>
                    <h6>Contacto: 664462959</h6>
                    <a href="https://www.linkedin.com/in/william-gonz%C3%A1lez-onatra-113825232/" target="_blank">LinkedIn</a>
                    <a href="https://github.com/willi0710/Portafolio" target="_blank">Github</a>

                </div>
            </div>
        </div>
    </header>
    <div class="row primary-border-subtle">
        <div class="col-md-6 my-3" >
            <div class="card">
                <div class="card-body p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h4 class="text-center">Habilidades Tecnicas</h4><br>
                    <ul class="lista-sin-viñetas">
                        <li>Informatica y Ciberseguridad</li>
                        <li>Fundamentos analista de SOC</li>
                        <li>Sistemas Operativos (Windows, Linux)</li>
                        <li>Estándares ISO 27001, NIST, COBIT, SGSI.</li>
                        <li>Programación Python, Django, HTML, CSS</li>
                        <li>Análisis de tráfico de red (Wireshark)</li>
                        <li>Herramientas de seguridad en Kali Linux</li>
                        <li>Análisis forense con Autopsy</li>
                        <li>Virtualización (VirtualBox, VMware).</li>   
                        <li>Comunicación técnica y no técnica</li>
                        <li>Microsoft Office</li>
                        <li>Gestión de Equipos</li><br>
                        <h6>Idiomas</h6>
                        <li>Ingles Tecnico</li>
                        <li>Español Nativo</li><br> 
                     
                                               
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6 my-3">
            <div class="card">
                <div class="card-body p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                    <h4 class="text-center">Formacion Academica</h4><br>
                    <ul class="lista-sin-viñetas">
                        <h6>Especialización en seguridad Informática - 12/2024</h6>
                        <li>Universidad Nacional Abierta y a Distancia UNAD</li><br>
                        <h6>Ingeniero Informatico - 08/2023</h6>
                        <li>Universidad Nacional Abierta y a Distancia UNAD</li><br>
                        <h6>Tecnólogo en Análisis y desarrollo de sistemas de información - 03/2020</h6>                        
                        <li>Servicio Nacional de Aprendizaje SENA</li><br>
                        <h4 class="text-center">Cursos y certificaciones</h4>
                        <h6>CP Seguridad Informática - 06/2025</h6>
                        <li>Microsistemas Arrecife, Lanzarote, España </li><br>
                        <h6>Analista Junior en Ciberseguridad - 12/2024</h6>
                        <li>Cisco Networking Academy</li><br>
                        <h6>SOC Analyst Learning Path 10/2024</h6>
                        <li>Letsdefend Blue Team Training</li>
                                                       
                    </ul>
                </div>
            </div>
        </div>
        
    </div>
    
    {% endblock%}
</body>
</html>

miPortafolio/templates/partials/navbar.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
        
</head>
<body>
    
  <nav class="navbar navbar-expand-lg bg-primary navbar-dark rounded-4 fixed-top" >
    <div class="container">
      <a class="navbar-brand" href="/">William Gonzalez Onatra</a>
     
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Perfil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'explaboral' %}">Experiencia Laboral</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'proyectos:project' %}">Proyectos</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a href="{% static 'miPortafolio/HV_WILLIAM.pdf' %}" class="btn btn-success btn-sm " target="_blank">Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</body>
</html>

proyectos/templates/proyectos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyectos</title>
</head>
<body>

    {% extends 'base.html' %}

    {% block content %}



    <div class="row">
        
        {% for proy in projects %}
        
        <div class="col-md-4 p-3">
            <div class="card">
                <img src="{{proy.image.url}}" alt="{{proy.title}}" class="img-fluid">
                <div class="card-body">
                    <h2>{{proy.title}}</h2> 
                    <p>Creado: {{proy.created}}</p>
                    <p>Actualizado: {{ proy.updated|date:"d M Y H:i" }}</p>
                    <p class="p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">{% if proy.link %}
                        <a href="{{proy.link}}" class="" target="_blank">{{proy.link}}</a>
                    {% endif %} <br><br>
                    {{proy.description}}
                              
                    </p>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>      

    {% endblock %}
    
</body>
</html>